model_path: "model/latest.pth"
use_cuda: True

# for development only
board_size: 9

mcts:
  record_data: True
  save_data: False
  data_path: "data/mcts.json"
  verbose: False

train:
  data_path: "data/mcts.pt"